version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=5351816125:AAHJf8d9vT_hEQzZ4D2mQopkrqNk9ItnS80
      - user_ids=1937215328
      - group_ids=-1001510312836
      - PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped
